version: '3.3'

services:
  cassandra:
    image:  cassandra
    container_name: cassandra
    volumes:
      - ./dbdata/cassandra-1:/var/lib/cassandra:rw
    restart: always
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: mysqlcrud
      MYSQL_PASSWORD: mysqlcrud



volumes:
  dbdata:
# this compomse no has it https://thepracticaldeveloper.com/2017/12/11/dockerize-spring-boot/ , but  that exmaple is beautiful because implements scale